name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kubescape/github-action@main
        #continue-on-error: false
        continue-on-error: true
        with:
          format: sarif
          outputFile: results.sarif
          account: 9ca2cefc-9ecb-4750-b353-0b5a6e427306
          #failedThreshold: 80
      - name: Upload Kubescape scan results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
